# Setup
title: Karl Lamothe
description: Aquatic Science Biologist
url: https://KarlLamothe.github.io
paginate: 5
avatar: /Profile_picture.jpeg
cover_image: /Algonquin.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: KarlLamothe
  card: summary
logo: logo.png
social:
  name: Karl Lamothe
  links:
    - https://twitter.com/KarlLamothe
    - https://github.com/KarlLamothe
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Karl Lamothe
  url: https://github.com/KarlLamothe/
  email: karl.lamothe@alum.utoronto.ca
